import "./globals.css";
import Sidebar from "../components/ui/modules/Sidebar";
import Header from "@/components/ui/modules/Header";
import localFont from "next/font/local";
import MuiProvider from "@/components/partials/provider/MuiProvider";


export const metadata = {
  title: "Store Admin Panel",
  description: "Generated by create next app",
};

const yekan = localFont({
  src: [
    {
      path: "../../public/fonts/YekanBakh-Light.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakh-Regular.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakh-Bold.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakh-Heavy.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/YekanBakh-Fat.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
       <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <body className={yekan.className}>
        <MuiProvider>
        <div className="main">
          <Header />
          <div className="contentMain flex">
            <div className="sidebarWrapper w-[18%]">
              <Sidebar>{children}</Sidebar>
            </div>
          </div>
        </div>
        </MuiProvider>
      </body>
    </html>
  );
}
