import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "../components/ui/modules/Sidebar";
import Header from "@/components/ui/modules/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <div className="main">
       <Header />
       <div className="contentMain flex">
        <div className="sidebarWrapper w-[18%]">
          <Sidebar>{children}</Sidebar>
        </div>
       </div>
       </div>
      </body>
    </html>
  );
}
